# Marketing Campaign Statistical Validation

## Task 4 – Data Storytelling & Statistical Validation

This notebook validates key business findings using statistical hypothesis testing.

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import ttest_ind

In [21]:
df = pd.read_csv("../data/marketing_campaign.csv", sep="\t")
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [22]:
df = df.dropna(subset=["Income"])

df["Total_Spending"] = (
    df["MntWines"] +
    df["MntFruits"] +
    df["MntMeatProducts"] +
    df["MntFishProducts"] +
    df["MntSweetProducts"] +
    df["MntGoldProds"]
)

df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Total_Spending
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,0,0,0,0,0,0,3,11,1,1617
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,0,0,0,0,0,0,3,11,0,27
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,0,0,0,0,0,0,3,11,0,776
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,0,0,0,0,0,0,3,11,0,53
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,0,0,0,0,0,0,3,11,0,422

# Hypothesis Testing

### Null Hypothesis (H0)

There is no significant difference in spending between high-income and low-income customers.

### Alternative Hypothesis (H1)

There is a significant difference in spending between high-income and low-income customers.

In [23]:
median_income = df["Income"].median()

high_income = df[df["Income"] >= median_income]

low_income = df[df["Income"] < median_income]

print("High Income Customers :", len(high_income))
print("Low Income Customers :", len(low_income))

High Income Customers : 1108
Low Income Customers : 1108

In [24]:
t_stat, p_value = ttest_ind(
    high_income["Total_Spending"],
    low_income["Total_Spending"],
    equal_var=False
)

print("T Statistic :", t_stat)
print("P Value :", p_value)

T Statistic : 52.96400723203524
P Value : 0.0

In [25]:
if p_value < 0.05:
    print("Reject the Null Hypothesis")
    print("Income has a statistically significant effect on customer spending.")
else:
    print("Fail to Reject the Null Hypothesis")
    print("Income does not have a statistically significant effect on customer spending.")

Reject the Null Hypothesis
Income has a statistically significant effect on customer spending.